### ISSUE TITLE
Unable to load MLNX modules after installing new kernels

### ISSUE THREAD

**Issue by SCDESPERTATE** [BarrinXu/FaaSMem#1]
I ran the c6220 instances on CloudLab with `RDMAc6220` profile. After compiling the kernel provided in the repository under directory '[linux-6.1.55-fastswap](https://github.com/BarrinXu/FaaSMem/tree/main/linux-6.1.55-fastswap)' and installing it,
the error appeared as follows after running the command `sudo /etc/init.d/openibd restart`

```
Unloading HCA driver:                                      [  OK  ]
Module mlx4_core does not exist, skipping...               [FAILED]
Module mlx4_ib does not exist, skipping...                 [FAILED]
Module mlx4_core does not exist, skipping...               [FAILED]
Module mlx4_en does not exist, skipping...                 [FAILED]
Module mlx5_core does not exist, skipping...               [FAILED]
Module mlx5_ib does not exist, skipping...                 [FAILED]
Module mlx5_fpga_tools does not exist, skipping...         [FAILED]
Module ib_umad does not exist, skipping...                 [FAILED]
Module ib_uverbs does not exist, skipping...               [FAILED]
Module ib_ipoib does not exist, skipping...                [FAILED]
Loading HCA driver and Access Layer:                       [  OK  ]
Module rdma_cm does not exist, skipping...                 [FAILED]
Module ib_ucm does not exist, skipping...                  [FAILED]
Module rdma_ucm does not exist, skipping...                [FAILED]
```

Is there anything I missed in setting up the environment? I tried to reinstall the MLNX_OFED_LINUX-4.9-7.1.0.0 driver, but got error 
```
/var/lib/dkms/mlnx-ofed-kernel/4.9/build/include/linux/sched/mm.h:54:27: error: 'struct mm_struct' has no member named 'core_state'; did you mean 'arg_start'?
        return likely(!mm->core_state);
                           ^
include/linux/compiler.h:77:40: note: in definition of macro 'likely'
 # define likely(x) __builtin_expect(!!(x), 1)
```

seems the driver is incompatible with newly installed kernel...

**Comment by LauYeeYu** [comment]
@SCDESPERTATE Can you please paste the output of `uname -a` on your server?

**Comment by BarrinXu** [comment]
@SCDESPERTATE 
Please provide a more detailed procedure of how you install the kernel and the RDMA driver.
After complete the step of [Install the modified Linux 6.1 kernel on the compute node](https://github.com/BarrinXu/FaaSMem?tab=readme-ov-file#install-the-modified-linux-61-kernel-on-the-compute-node), you should install the RDMA driver following the instructions in [Install the RDMA driver and compile Fastswap on the compute node and the memory node](https://github.com/BarrinXu/FaaSMem?tab=readme-ov-file#install-the-rdma-driver-and-compile-fastswap-on-the-compute-node-and-the-memory-node), then you can check the openibd status.

**Comment by SCDESPERTATE** [comment]
Here is a more detailed procedure.

1. Clone the repository from [FaaSMem](https://github.com/BarrinXu/FaaSMem.git)
2. Enter `linux-6.1.55-fastswap directory`. Execute `bash install_kernel.sh`, then the machine reboot 
following error message occurred as before...
```
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/e1000e-dkms/3.4.2.3/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/i40e-dkms/2.7.29/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/i40evf-dkms/3.6.15/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/igb-dkms/5.3.5.22/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/ixgbe-dkms/5.5.3/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/ixgbevf-dkms/4.5.2/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/kernel-mft-dkms/4.14.0/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/mlnx-ofed-kernel/4.9/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/mpt3sas-dkms/26.00.00.00/build/make.log for more information.
Error! Bad return status for module build on kernel: 6.1.55-fastswap (x86_64)
Consult /var/lib/dkms/rshim/1.18/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 6.1.55-fastswap /boot/vmlinuz-6.1.55-fastswap
update-initramfs: Generating /boot/initrd.img-6.1.55-fastswap
```
3. after the reboot, enter `Fastswap` directory and execute `bash install_rdma.sh`
```
Unpacking ibutils (1.5.7-5ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/ibutils_1.5.7-5ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/ibdiagnet', which is also in package ibutils2 2.1.1-0.121.MLNX20200324.g061a520.49017
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../rdmacm-utils_17.1-1ubuntu0.2_amd64.deb ...
Unpacking rdmacm-utils (17.1-1ubuntu0.2) ...
dpkg: error processing archive /var/cache/apt/archives/rdmacm-utils_17.1-1ubuntu0.2_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/cmtime', which is also in package librdmacm-utils 41mlnx1-OFED.4.7.3.0.6.49017
Errors were encountered while processing:
 /var/cache/apt/archives/ibutils_1.5.7-5ubuntu1_amd64.deb
 /var/cache/apt/archives/rdmacm-utils_17.1-1ubuntu0.2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

the output of the command `uname -a` is 
```
Linux node-0.aabb-204325.rmpf001-pg0.apt.emulab.net 6.1.55-fastswap #1 SMP PREEMPT_DYNAMIC Wed Apr 24 23:05:13 MDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```
4. error reported as before after running the command `sudo /etc/init.d/openibd restart`

I admit that the Ubuntu version is Ubuntu 18.04 LTS (Bionic Beaver) not 22.04 LTS as listed in the `README.md` of this project, but I am skeptical whether the version would affect the outcome since the driver is relevant to the kernel only?

**Comment by BarrinXu** [comment]
@SCDESPERTATE Please try 22.04 LTS (On cloudlab, click start the experiment, then select OS image of ubuntu 22.04), 22.04 should work.

**Comment by SCDESPERTATE** [comment]
Thanks for your quick reply! But is there any option in the profile `RDMAc6220` that can help configure the OS version? Or could you recommend a suitable profile for experiment?
What I saw after choosing the `RDMAc6220` profile and clicking button `Next` is as follows, it directly jumped to the third tab...
![image](https://github.com/BarrinXu/FaaSMem/assets/74419971/44687935-9580-4a8a-a49a-d06c517f10ee)
Please forgive my awkwardness.

**Comment by BarrinXu** [comment]
@SCDESPERTATE 
You can try these steps
1. 
![image](https://github.com/BarrinXu/FaaSMem/assets/58480159/b7671c08-06d0-49b8-b31a-b5d5b913a5f6)
2.
![image](https://github.com/BarrinXu/FaaSMem/assets/58480159/b1a35af4-215f-4783-8db2-97b06604142f)

**Comment by SCDESPERTATE** [comment]
After changing the OS version to Ubuntu 22.04 LTS, everything went smoothly.
Appreciate @BarrinXu 's and @LauYeeYu 's  patience.
